// <auto-generated />

/// <summary>Provides access to the git information for the current assembly.</summary>
public partial class GitInfo
{
    public const string GitRoot = @"$[GitRoot]";

    /// <summary>IsDirty: $[GitIsDirty]</summary>
    public const bool IsDirty = $[GitIsDirty];

    /// <summary>Repository URL: $[GitRepositoryUrl]</summary>
    public const string RepositoryUrl = @"$[GitRepositoryUrl]";

    /// <summary>Branch: $[GitBranch]</summary>
    public const string Branch = @"$[GitBranch]";

    /// <summary>Commit: $[GitCommit]</summary>
    public const string Commit = @"$[GitCommit]";

    /// <summary>Sha: $[GitSha]</summary>
    public const string Sha = @"$[GitSha]";

    /// <summary>Commit date: $[GitCommitDate]</summary>
    public const string CommitDate = @"$[GitCommitDate]";

    /// <summary>Commits on top of base version: $[GitCommits]</summary>
    public const string Commits = @"$[GitCommits]";

    /// <summary>Tag: $[GitTag]</summary>
    public const string Tag = @"$[GitTag]";

    /// <summary>Base tag: $[GitBaseTag]</summary>
    public const string BaseTag = @"$[GitBaseTag]";
}
