// <auto-generated />

$(Context)

$(VersionAttributes)

$(Namespace)

/// <summary>Provides access to the git information for the current assembly.</summary>
public partial class GitInfo
{
    public const string GitRoot = @"$(GitRoot)";

    public const bool IsDirty = $(GitIsDirty);

    public const string Branch = @"$(GitBranch)";

    public const string CommitShortHash = @"$(GitCommitShortHash)";

    public const string CommitHash = @"$(GitCommitHash)";

    public const string CommitDate = @"$(GitCommitDate)";

    public const string Tag = @"$(GitTag)";
}
